### ISSUE TITLE
Binding/module issue. 

### ISSUE THREAD

**Issue by Zebrainbow** [cvetaevvitaliy/Radiomaster_TX16S#1]
Wired the board up like you showed in the picture. RX to horizontal pin, TX to the vertical. Plugged in the R9M 2019 module and tried to bind, but the module doesn’t appear to be communicating. Verified my solder connections. Module seems to be blinking like it does during registration on a functioning qx7. I did notice that no firmware information is listed for the external module on the information page. Does this require any other software or specific firmware to work? I’m running R9 flex 1.30 on the module and receiver.

**Comment by Zebrainbow** [comment]
![DF472C1D-18B0-41D5-94BE-AAB96DDB3FCB](https://user-images.githubusercontent.com/36449838/88353462-25cd9180-cd23-11ea-996a-0e78dc9274f0.jpeg)

**Comment by cvetaevvitaliy** [comment]
Hi! Thanks you, for repeating this mod, I update instruction, no the firmware is working, I noticed that on some Radio you need to connect the 2 pin XJT module to "gate" transistor 
![2020-07-14 22 38 38](https://user-images.githubusercontent.com/26421560/88368122-10de1600-cd96-11ea-83e4-ea32d914dd72.jpg)
![2020-07-14 22 30 23](https://user-images.githubusercontent.com/26421560/88368129-13d90680-cd96-11ea-8355-b691bf4ca282.jpg)
![IMG_6007](https://user-images.githubusercontent.com/26421560/88368265-5ac6fc00-cd96-11ea-9659-43b2885283e4.jpg)
![IMG_6008](https://user-images.githubusercontent.com/26421560/88368276-61557380-cd96-11ea-8745-3e10f0ef816d.jpg)

**Comment by Zebrainbow** [comment]
Thanks! That worked. After soldering the new connection, access protocol works successfully with R9 flex firmware.

**Comment by fishe972** [comment]
i tried with the 3rd wire . and worked for me too.great job.
