### ISSUE TITLE
telemetry for internal module not working

### ISSUE THREAD

**Issue by lamnesique** [cvetaevvitaliy/Radiomaster_TX16S#2]
hi, before all, thanks for your great job

i do the mod and it work fine on my tx16 with 3 wires, bind access succefully, but i find that with your firmware a lost all internal multimodule telemetry. i update it with last version but still the same issue, if i put an external multimodule it work fine, and if i reflash 2.3.9 otx firmware always with the 3 wires solders it show telemetry.

and is it possible to appli access mod to a french firmware?

thanks by advance

**Comment by cvetaevvitaliy** [comment]
Thanks for your interest my mod!

I do not use the multi-protocol module, but thanks for the feedback, I will find the reason and fix it.
Of course, you can buld FW with French language
see this branch https://github.com/cvetaevvitaliy/opentx/tree/RadiomasterTX16S_ACCESS
You need add -DTRANSLATIONS=FR compile options

**Comment by cvetaevvitaliy** [comment]
Or use this firmware, I builded it for you 
[TX16S_firmware_fr.zip](https://github.com/cvetaevvitaliy/Radiomaster_TX16S/files/5062320/TX16S_firmware_fr.zip)

**Comment by lamnesique** [comment]
thanks for all

**Comment by cvetaevvitaliy** [comment]
> thanks for all

I fixed internal multimodule
