### ISSUE TITLE
Issue with 868mhz

### ISSUE THREAD

**Issue by shro70** [cvetaevvitaliy/Radiomaster_TX16S#3]
Hi.
First thank you for you incredibly good work.
I ordered a r9m2019 with a R9MX receiver so your mod is the only way to use them on my TX16s.( No accst for the R9MX receiver.)

I  have an issue with the EU 868mhz  config .The radio and receiver work in 915mhz but not in 868mhz. The R9MX red light continue to rapidly flash even after I get the "bind succesfull" message. I tried both Flex and LBT firmware on the R9m2019 and MX but still not working.

Another issue is the input lag with either fport or sbus +smart port. I use a F722 wing.

Which version are you using?
I'm in europe and all my antenna are for LBT so I prefer to use 868mhz.

Thanks again for your mid and firmware.

**Comment by cvetaevvitaliy** [comment]
Hello! Thank! 
I am using FLEX firmware on receiver and xjt module.
This firmware dual band 868 and 915, during the bind, a message will pop up which frequency you want to use.

**Comment by shro70** [comment]
I'm using flex firmware too. The last one to be found on .  I select the 868mhz band in the pop-up message ,get the succesfull bind message but after the red light continue to flash.
It work when I use 915mhz but get big lag in servo's reaction and inav receiver tab.
Really strange.
I think I will sell the r9mx and stick with accst.

**Comment by cvetaevvitaliy** [comment]
But need make bind and after register RX
For example step:
1. Push button bind in RX
2. Select bind in TX
3. Bind complete, green led power in in RX
4. Set register RX menu in your TX
5. Reconnect power RX, wait and see your RX name in menu TX
6. Finish

**Comment by cvetaevvitaliy** [comment]
I don't know, FrSKy use very bad algorithm for bind RX, but price RX and TX compared to TBS very good

**Comment by shro70** [comment]
Thanks a lot for your help. I'm was able to bind in 868mhz mode too but I still have my 0.3 to 0.5s lag like in 915mhz. I'm lost.  I have fport and telemetry working , a rssi of 70db but this fucking lag make me crazy.
I'm lost. My RX green led is slowly flashing . Not a solid green 
I tried reflashing everything. Still the lag.
I've dozen Rxsr, ia6b,flit10, jumper r1 but this fucking R9 system  give me a lot of headache.
Thanks again

**Comment by cvetaevvitaliy** [comment]
I have never used R9MX receiver, I have no experience in using R9MX
I use R9MM only ( or R9 slim for my long range setup ) because it fits perfectly in my flight controller - GravityF7 
https://flymod.net/item/flymod_gravity_f7 
P.S. This FC - my development ;)

**Comment by cvetaevvitaliy** [comment]
@shro70 may be select and recheck FW your RX R9MX, and recheck F.Port setings in your TX
see video https://youtu.be/9NwFpAAEJiQ

**Comment by shro70** [comment]
Thanks again Vitaly .
Yes I have Fport option activated in TX setting but even sbus output is laggy. I'm using the access 1.31 flex firmware for the R9 MX ( the only firmware released it seem)
I just received a R9MM and I get the same result if I use access. I tried reflashing opentx,(with your modded version of), the R9m2019 and rx firmware. Still same result : lag ,bad rssi and a flashing green light.

With the R9MM and accst flex 0 everything work great . Good rssi,good range ,no lag.
Hope frsky release a accst firmware for the MX.

Oh and great FC. Maybe my next one .

**Comment by cvetaevvitaliy** [comment]
Maybe the problem is not in the receiver, what is your flight controller and sw for controller ?

**Comment by shro70** [comment]
F722 wing with inav 2.52. I will try on a F405 wing this afternoon but I think the issue is between the TX and RX in access because it work peefectly in Accst . I ordered 2 anothers R9MM and the R9MX RX will probably sit in my drawer in the future.
When I use access I don't get a solid green light on the RX like I get with accst .so the RX is bound but communication is broken half the time hence the lag .
Really strange issue .
Thanks again.
